# Generated by Django 5.0.6 on 2024-06-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_temp', models.CharField(choices=[('hot', 'Hot'), ('iced', 'Iced')], default='hot', max_length=4)),
                ('drink_flavor', models.CharField(choices=[('Vanilla', 'Vanilla'), ('Hazelnut', 'Hazelnut'), ('Caramel', 'Caramel'), ('White Mocha', 'White Mocha'), ('Mocha', 'Mocha'), ('Toffee', 'Toffee'), ('Butter Scotch', 'Butter Scotch'), ('Sugar Free Vanilla', 'Sugar Free Vanilla'), ('Sugar Free Caramel', 'Sugar Free Caramel'), ('Sugar Free Mocha', 'Sugar Free Mocha')], default='Vanilla', max_length=20)),
                ('drink_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_temp', models.CharField(choices=[('hot', 'Hot'), ('iced', 'Iced')], default='iced', max_length=4)),
                ('drink_kids_choices', models.CharField(choices=[('milk', 'Milk'), ('lemonade', 'Lemonade'), ('juice', 'Juice')], default='juice', max_length=15)),
                ('drink_kids_flavor_choices', models.CharField(choices=[('chocolate', 'Chocolate'), ('strawberry', 'Strawberry'), ('mango', 'Mango'), ('raspberry', 'Rapsberry'), ('watermelon', 'Watermelon'), ('whipped cream', 'Whipped Cream')], default='strawberry', max_length=20)),
                ('drink_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_temp', models.CharField(choices=[('hot', 'Hot'), ('iced', 'Iced')], default='hot', max_length=4)),
                ('drink_tea_type', models.CharField(choices=[('Black', 'Black'), ('Green', 'Green'), ('Herbal', 'Herbal'), ('English Breakfast', 'English Breakfast'), ('Rooibos', 'Rooibos'), ('Oolong', 'Oolong'), ('Earl Grey', 'Earl Grey'), ('Masala Chai', 'Masala Chai')], default='Black', max_length=20)),
                ('drink_tea_flavor', models.CharField(choices=[('Strawberry', 'Strawberry'), ('Peach', 'Peach'), ('Mango', 'Mango'), ('Lychee', 'Lychee'), ('Vanilla', 'Vanilla'), ('Raspberry', 'Raspberry'), ('Peppermint', 'Peppermint'), ('Simple Syrup', 'Simple Syrup')], default='Simple Syrup', max_length=20)),
                ('drink_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=6)),
            ],
        ),
    ]
