# Generated by Django 5.0.6 on 2024-06-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='drink_type',
            field=models.CharField(choices=[('latte', 'Latte'), ('pour_over', 'Pour Over'), ('drip_brew', 'Drip Brew'), ('americano', 'Americano'), ('capuccino', 'Capuccino')], default='latte', max_length=20),
        ),
    ]
