# Generated by Django 5.0.6 on 2024-06-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='drink_flavor',
            field=models.CharField(choices=[('Vanilla', 'Vanilla'), ('Hazelnut', 'Hazelnut'), ('Caramel', 'Caramel'), ('White Mocha', 'White Mocha'), ('Mocha', 'Mocha'), ('Toffee', 'Toffee'), ('Butterscotch', 'Butterscotch'), ('Sugar Free Vanilla', 'Sugar Free Vanilla'), ('Sugar Free Caramel', 'Sugar Free Caramel'), ('Sugar Free Mocha', 'Sugar Free Mocha')], default='Vanilla', max_length=20),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='drink_type',
            field=models.CharField(choices=[('latte', 'Latte'), ('pour_over', 'Pour Over'), ('drip_brew', 'Drip Brew'), ('americano', 'Americano'), ('cappuccino', 'Cappuccino')], default='latte', max_length=20),
        ),
        migrations.AlterField(
            model_name='kids',
            name='drink_kids_flavor_choices',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('strawberry', 'Strawberry'), ('mango', 'Mango'), ('raspberry', 'Raspberry'), ('watermelon', 'Watermelon'), ('whipped cream', 'Whipped Cream')], default='strawberry', max_length=20),
        ),
    ]
